17:49:21,255 (main) WARN  [DataNucleus.Datastore.Schema] - You have specified the default schema as datastoreidentity8 but for this datastore this has been changed to DATASTOREIDENTITY8. This is likely due to missing quote characters, or the datastore storing things in a different case
17:49:21,606 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,680 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,697 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,713 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,745 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,759 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,772 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,784 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,810 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,821 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,837 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,852 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,863 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,874 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,885 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,901 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,916 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:49:21,927 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE DATASTOREIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE DATASTORE_ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:336)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.SQLController.doExecuteStatementUpdate(SQLController.java:463)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:396)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:321)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:687)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:646)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1180)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:221)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:664)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:636)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1284)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5540)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2356)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2282)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2178)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:814)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

